# Generated by Django 3.0.7 on 2021-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time', models.TextField()),
                ('sender', models.TextField()),
            ],
        ),
    ]
