# Generated by Django 3.0.7 on 2021-05-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
