# Generated by Django 3.0.7 on 2021-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesite', '0002_auto_20210513_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.TextField()),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
